### PR TITLE
Redesign Front End to match UniStudents mobile application

### PR DESCRIPTION
**Pull request by JohnSandalis**
I’ve redesigned the front end of the UniTesters client so that it looks like the mobile application. It is fully responsive for all screen sizes.

These changes improve the user interface and provide access to UniStudents from a web browser. Since this version is still being used for testing, it highly improves the user experience of anyone who takes part in it, and lets testers understand how the actual application looks.

The changes to the interface were accomplished using HTML, SCSS, and JavaScript, while Bootstrap was removed. Additionally, code from the mobile app was used for creating the charts with Chart JS.

### CODE REVIEW

**Comment by NickSklA** [comment]
Thank you for your contribution @JohnSandalis. We really appreciate the time and effort you put into this. The redesign looks fantastic and is indeed very close to the mobile app.

We will take some time to review your code and come back to you asap. 🙌

**Review by donfn — APPROVED** [review]

**Comment by donfn** [comment]
👌👌🔥

**Review by JexSrs — APPROVED** [review]
Seems right.

**Comment by nickdelis** [comment]
Excellent job @JohnSandalis 👏👏!

**Pull request merged**
